name: Deploy to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /opt/elevated-sheets
          git pull origin main
          cd platform
          docker compose -f docker-compose.prod.yml -p elevated up --build -d
